### ISSUE TITLE
Unrecognized function or variable 'flipping'.

### ISSUE THREAD

**Issue by daviddmc** [lcorgra/RGDSVR#2]
Hi, I was trying to run the algorithm with my own data and got an error of missing function 'flipping'. What is the definition of this function? Thanks.

The details of the error msg:

```
Unrecognized function or variable 'flipping'.

Error in sincRigidTransformQuick (line 45)
        if et{5}(m)==1;x=flipping(x,et{4}{m});end%FLIPPING FOR LARGER THAN 90DEG ROTATIONS

Error in svrEncode (line 39)
        if
        useT>4;x=real(sincRigidTransformQuick(x,precomputeFactorsSincRigidTransformQuick(svr.kGrid,svr.rGrid,dynInd(svr.TV,v,5),1,0,[],1,svr.cGrid),1,svr.FT));end

Error in svrCG (line 17)
    svr=svrEncode(svr,-1);

Error in svrAlternateMinimization (line 35)
    svr=svrCG(svr,3+(nF<2)+(nF<3));
```

**Comment by lcorgra** [comment]
Hi, added flipping.m function to the repo, so you could try again. However, need to resort to this function may mean the geometry of your data (arrangement of stacks) hasn't been contemplated in my tests. If you start to see weird artifacts, oscillating, or divergence of reconstruction, please report, as we may need a more sophisticated fix. Thanks!

**Comment by lcorgra** [comment]
Sorry, shifting.m was also missing, just committed.

**Comment by daviddmc** [comment]
Thanks for the fix!
